### ISSUE TITLE
Which part of code is the one directly commanding drone?

### ISSUE THREAD

**Issue by koalapenguins** [perrytsao/pc-drone#1]
Hi, i've been analyzing the code, is it correct that this part of the code is the one directly commanding the movements of the cx-10?

`## Serial comms - write to Arduino`
        `throttle=clamp(throttle, 1000, 2000)`
       ` rudder=clamp(rudder, 1000, 2000)`
        `command="%i,%i,%i,%i"% (throttle, aileron, elevator, rudder)`
       ` print "[PC]: "+command`
       ` arduino.write(command+"\n")`

cheers

**Comment by perrytsao** [comment]
Yes, that is essentially it.  The "arduino.write(command+"\n") line is the one that actually sends the command string to the Arduino.  The rest of it just constructs the string and the prints it out to the terminal for debug purposes.
