### ISSUE TITLE
Binding to cx-10 procedure

### ISSUE THREAD

**Issue by koalapenguins** [perrytsao/pc-drone#2]
Hi, i think im close to flying the drone with your python code 

Where exactly in the code of fly_drone.py does it start binding to the drone (eg: simulating the minimum throttle, maximum throttle, minimum throttle sequence)?

Im actually trying to run the serial_test.py file from your other repo, which uses the same command as this file (arduino.write())

at https://github.com/perrytsao/nrf24_cx10_pc/blob/master/serial_test.py

though i can't post comments there

(im just trying to test flight the drone with manual keyboard controls before moving on to opencv and the real fun ^^)

Cheers

**Comment by perrytsao** [comment]
The binding sequence is done in the firmware on the Arduino.  The way I usually do it is to turn on the Arduino (one of the LEDs will flash), and then turn on the CX-10.  I think one of the LEDs will then turn on solid on the Arduino.

Nothing needs to be done in Python to bind it except that buried in the code somewhere I do close and open the serial connection which causes the firmware in the Arduino to reset and allow it to bind to a different CX-10.

Good luck!

**Comment by koalapenguins** [comment]
awesome, it flies now!

for the benefit of future people who might see this code, i followed the sequence in which you turned on your devices. i first turned on the arduino, then the cx-10. Afterwards, i kept resetting the arduino (by pressing its on-board reset button) until i saw the console messages:

"cx10-initialized and bound"
"init protocol complete."

and it takes around a dozen or so presses of the throttle until the propellers start rotating for me.

It leaves me to my last question: is it normal to reset the arduino until i get a "good" bind? it took me a few resets before they managed to communicate.

Cheers!

![foo2](https://cloud.githubusercontent.com/assets/24664723/21712123/bc44394a-d42d-11e6-8d4f-e4f16f7193ef.png)
